# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='doctors',
        ),
    ]
