# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-30 16:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20180525_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='address',
            field=models.CharField(default='asdf', max_length=255),
        ),
        migrations.AddField(
            model_name='doctors',
            name='bio',
            field=models.TextField(default='asdf'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='city',
            field=models.CharField(default='asdf', max_length=255),
        ),
        migrations.AddField(
            model_name='doctors',
            name='discipline',
            field=models.CharField(default='asdf', max_length=20),
        ),
        migrations.AddField(
            model_name='doctors',
            name='dob',
            field=models.DateField(default=datetime.date(2018, 5, 30)),
        ),
        migrations.AddField(
            model_name='doctors',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctors',
            name='state',
            field=models.CharField(default='asdf', max_length=255),
        ),
        migrations.AddField(
            model_name='doctors',
            name='zipcode',
            field=models.IntegerField(default=69),
        ),
    ]
