# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20180525_1639'),
        ('patient', '0002_auto_20180525_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='doctor.doctors'),
            preserve_default=False,
        ),
    ]
