# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-26 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20180525_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_id',
            field=models.IntegerField(default=1),
        ),
    ]
