# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20180525_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField(default=0)),
                ('diastolic', models.IntegerField(default=0)),
                ('bloodsugar', models.DecimalField(decimal_places=2, max_digits=4)),
                ('heartrate', models.IntegerField(default=0)),
                ('patient_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
