# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address2',
        ),
        migrations.AddField(
            model_name='patient',
            name='diabetes',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entries',
            name='bloodsugar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
